### ISSUE TITLE
What should we do if a user does not have a profile picture?

### ISSUE THREAD

**Issue by forabi** [hollowverse/design#10]
Users may be able set up a profile without a profile picture. How should we handle this case?

Should we display a fallback image (like one of [these](https://www.freepik.com/free-vector/man-and-woman-avatars_766415.htm#term=avatar&page=1&position=3))? If so, an SVG image be good for that.

**Comment by Maxgrb** [comment]
@forabi @msafih should we use custom pic or Facebook default picture?

My thoughts: if we use Facebook comments widget (where Facebook uses default pics), then seems it's better to use Facebook default picture everywhere for consistency?

**Comment by forabi** [comment]
Using Facebook default picture makes sense to me. We can go with that for
now.

في الأربعاء، ٨ تشرين الثاني، ٢٠١٧ ٩:٤٢ م Max Gorbachev <
notifications@github.com> كتب:
