### ISSUE TITLE
Provide design for other states of Notable Person's page

### ISSUE THREAD

**Issue by forabi** [hollowverse/design#11]
## Error state
A notable person's page may fail to load due to a network error or a bug in our code. We need to handle this case and display an error message to the user.

Some of the reasons a page may fail to load:
  * Notable Person is not found in our database (404)
  * Internet connection is lost or slow
  * Something is wrong on our end (API is down, code bug, etc.)

## Loading state
Because our new website is designed as a web app that calls an API, there might be some time between the page is loaded and the content is rendered. We need to indicate to the user that we are loading the content instead of showing a blank page.

**Comment by forabi** [comment]
This might be relevant: https://www.npmjs.com/package/react-loading-skeleton

**Comment by Maxgrb** [comment]
@forabi updated. Please, check.

**Comment by forabi** [comment]
Looks great!

في الأربعاء، ٨ تشرين الثاني، ٢٠١٧ ٩:٤٣ م Max Gorbachev <
notifications@github.com> كتب:
