### ISSUE TITLE
Support event types in notable person's page

### ISSUE THREAD

**Issue by forabi** [hollowverse/design#12]
We are going to introduce different types of events about a notable person.

Example of event types:
* Donations (NP has donated to a purpose or an organization)
* Appearances (social events/places where the NP has appeared)
* Quotes

We need to show each type of event as a separate section in the NP's page. Under each section is a few of relevant events that belong to that event type. We _should not_ display _all_ the events of that type.

The types of events should still be easy to scan and the user should be able to understand what the page is about at a glance. This might need other modifications to the current design. The end goal is that the content is intuitive and does not need too much thinking to scan, digest, and understand. 

Each event type should have a "View More" link or button, clicking on which navigates the user to a sub-page that lists all the events for that NP under that type. The user should be able to click a in-app "back button" to go back to the main NP's page.

User comments should also be moved to the corresponding sub-pages, i.e. they should not be visible on the NP's main page.

**Comment by msafih** [comment]
@Maxgrb,

@forabi also brought up the point that with the current design, labels attract too much attention from every thing else. Can we somehow tone the labels down or give them less attention?

**Comment by Maxgrb** [comment]
@forabi @msafih could you describe what data each event should contain:

- Donation: date, name of an organisation, URL? Should it contain an user comments?
- Appearance: date, name of event/place, URL? User comments?
- Quotes fields will remained the same?

**Comment by forabi** [comment]
Closed by #15
