### ISSUE TITLE
Fix issue with user comment being covered by user profile picture

### ISSUE THREAD

**Issue by forabi** [hollowverse/design#14]
Here is an example of the issue:

![screenshot_20171109_135625](https://user-images.githubusercontent.com/1012761/32604375-10d3d956-c556-11e7-89c8-998e6e850075.png)

Ideally, the text should wrap around the image like this:

![espresso](https://user-images.githubusercontent.com/1012761/32623146-d4499cfe-c58d-11e7-9501-9f8cef0f29d2.jpg)

I actually tried implementing this using [CSS Shapes](https://www.html5rocks.com/en/tutorials/shapes/getting-started/), but we cannot define a shape on an absolutelty-positioned element. So I changed the image position to `relative`, set `float: right` and adjusted the position:

![screenshot_20171109_140848](https://user-images.githubusercontent.com/1012761/32604779-87d7ea5a-c557-11e7-806f-2159f39f3029.png)

(I have intentionally set `text-align: right` to show the text wrapping around a circle shape.

The problem is that we cannot keep the image at the bottom of the comment bubble unless we know exactly how tall the bubble will be, which cannot be known because the comments are of varying lengths.

Another problem is that CSS Shapes are only supported in Chrome and Safari, so we are going to need another solution or implement a fallback for browsers that do not support that feature.

**Comment by forabi** [comment]
Here is a minimal demo of CSS Shapes: http://jsbin.com/sezesevome/1/edit?css,output

**Comment by msafih** [comment]
@forabi @Maxgrb Speaking of these chat bubbles, I think they're too strong and demand attention away from the main event. It would be good to tone them down or redesign them some how.

**Comment by forabi** [comment]
No longer relevant. Closing.
