### ISSUE TITLE
Old content in the new Hollowverse

### ISSUE THREAD

**Issue by wholesomedev** [hollowverse/design#17]
We've decided that, as a temporary solution to create a path for migration, we want to bring the old content of Hollowverse as-is to the new Hollowverse.

In the new Hollowverse we have the concept of events contributed by users. In the old Hollowverse we just have articles written by Hollowverse staff. 

We want to bring the articles from the old Hollowverse and put them alongside the events on the new Hollowverse.

I'm thinking with the new content, the layout will look like this:

```
<Picture of NP/>

<Name of NP/>

<Labels/>

<Summary/>

<Events content of new Hollowverse>
  <Quotes/>
  <Donations/>
  <Appearances/>
  <Etc.../>
</Events content of new Hollowverse>

<Old article>
  /* No summary from the old articles since we'll 
  take the summary and put it on the top of the NP page */
  <Old article content about the NP's religious beliefs/>
  <Old article content about the NP's political beliefs/>
  <Sources/> /* Initially collapsed but can expanded */
  <Old article footer with author name and publish date/>
</Old article>

<Other interesting profiles section/>

<Facebook comments/>
```

We have all the pieces for the layout except for `<Old article>`. That's what we need the design for.

Thoughts?

**Comment by wholesomedev** [comment]
I'm not sure what we should title the section for the `<Old article>`. I was thinking "Editorial summary", but I don't know if that makes sense...

**Comment by forabi** [comment]
> `<Other interesting profiles section/> /* Not sure we should put this here or outside of <Old article> */`

I think it makes more sense to have interesting profiles outside of `<Old article>`, probably immediately before Facebook comments

**Comment by wholesomedev** [comment]
> I think it makes more sense to have interesting profiles outside of `<Old article>`, probably immediately before Facebook comments

Sounds good to me.

**Comment by Maxgrb** [comment]
@wholesomedev what is the `<Sources />`? Could you show it on the current Hollowverse or give more details?

**Comment by Maxgrb** [comment]
@wholesomedev seems I've found it, is it?

<img width="633" alt="screen shot 2017-12-11 at 14 40 09" src="https://user-images.githubusercontent.com/4107450/33833823-3892f12c-de81-11e7-9c25-e76725e70aaa.png">

**Comment by forabi** [comment]
@Maxgrb 

> seems I've found it, is it?

Yes, that is what `<Sources />` refer to.
