### ISSUE TITLE
Should we imitate the Facebook mobile app design?

### ISSUE THREAD

**Issue by wholesomedev** [hollowverse/design#18]
I opened our app today on my iPhone 8 Plus. To be honest, lack of content notwithstanding, I didn't feel that the design looked like an app.

So, I started thinking about the missing pieces...

It occurred to me that both Facebook and Hollowverse have the "profile" concept. On Facebook, a profile is for a user. On Hollowverse, a profile is for an NP. But we can repurpose the Facebook profile for our own use case, I think. So, should we imitate Facebook's mobile app design?

Take a look at this comparison:

*Note: I'm comparing with the Facebook iPhone app, not the Facebook mobile website, because the mobile website seems to be lagging behind the app in terms of design.*

<table>
<tr>
<td>
<img src="https://user-images.githubusercontent.com/26730388/33301769-95f3466c-d3ac-11e7-86c9-689b16158e94.png"/><br>
<img src="https://user-images.githubusercontent.com/26730388/33301833-ef60391c-d3ac-11e7-80ef-1f2f59feb648.png"/>

</td>
<td>
<img src="https://user-images.githubusercontent.com/26730388/33301738-4d615560-d3ac-11e7-87fb-5e4d6c329c04.png"/><br>
<img src="https://user-images.githubusercontent.com/26730388/33301873-26dc69f6-d3ad-11e7-944b-46ef56ad906f.png"/>
</td>
</tr>
</table>

If you look at the comparison above (or better yet open Hollowverse and the Facebook app on your phone), you notice that Facebook content uses the whole width of the device. There are either no margins or the margins are minimal. (Even by simply looking at the comparison above, you can see how the Facebook content *jumps* at you while Hollowverse appears receded.)

We can even repurpose the Facebook Post design for the Hollowverse Event.

What do you think?

**Comment by forabi** [comment]
I agree that the new NP pages still looks more like a document than an app page. While updating the design of the page, I experimented with full-width cards and events, and I think some tweaks could totally change the perception of the page.

I suggest we start by making the background color darker, and adjusting the width of the cards and events. I'm not sure what changes we should apply to the profile picture though.

**Comment by wholesomedev** [comment]
@forabi would you have any concern if we adopt more from the Facebook interface? I ask because I think there's a lot more we can adopt, like the following:

* The way the top bar morphs into a sticky search bar with the person's name pre-populated
* Font sizes
* Spacing between elements
* The top part of the profile where the user picture is laid on top of a background picture (we can look into a suitable style of computer generated art or something for the background picture)
* For Hollowverse Quote Event, we can format it as a Facebook Post such that:
  * Facebook user pic => NP pic
  * Facebook user name => NP name
  * Facebook post date => Event post date
  * Facebook post location => Source
  * Facebook post content => Quote
  * Location of Facebook reactions => Location of Event labels
  * Facebook post comments count => Event comments count
  * In the future we might also need to enable actions on an event, such as reporting it, tagging it, etc. For those things we can also use Facebook post bottom part, or the ··· for actions in the top right corner

The other benefit of adopting Facebook's layout is that many other apps are formatted this way too. So this relieves some cognitive load for consuming Hollowverse content for our users.

**Comment by forabi** [comment]
No concerns. I think it would look great.
