### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by wholesomedev** [hollowverse/design#21]
We need to design the search page of the new Hollowverse. 

The UX should be similar to that of Facebook app search. Here's what I mean:

Whenever the user focuses the search bar, the search page loads. The initial view of the search page is blank. Once the user starts typing, we can begin to show _preliminary_ list of NPs that match the search. At the bottom of this preliminary result page is a link that says "See results for [search term]".

After the user is done typing, the user can either select one of the NPs from the list of results or execute the search by either pressing "Enter" on their keyboard or pressing the "See results for [search term]" link at the bottom of the preliminary results page.

If the user selects an NP profile, they get redirected to the NP's page. If the user executes the full search (i.e. they press "Enter" or the "See results for [search term" link), one of two things may happen:

1. If there already are results on the page, the search box loses focus and the keyboard gets hidden. And the "See results for [search term]" link gets hidden
2. If there are no results on the page, we show a No Results page.

Facebook search works in the same way. You can inspect Facebook search on the Facebook app to see what I mean.

For each result item we can show the NP's image and name. ~Should we also show labels? Not sure.~ Let's not show anything else. At least not for v1.

Let me know if you have any thoughts on that.

**Comment by forabi** [comment]
> Once the user starts typing, we can begin to show preliminary list of NPs that match the search. At the bottom of this preliminary result page is a link that says "See results for [search term]".

This is where our current implementation differs. What should the preliminary list show? How it is different from the regular search results?

**Comment by wholesomedev** [comment]
@forabi I think what I was thinking about was: when do we show the "No results" state. If we already have this figured out in the current UX, then we can consider this issue complete.

If in the future we find ourself in need to change the UX, we can create another issue.

**Comment by forabi** [comment]
This is how the search page currently looks when no results are found:

![screen shot 2018-01-05 at 00 03 24](https://user-images.githubusercontent.com/1012761/34586259-e43286cc-f1ab-11e7-9e54-d055270d7587.png)

**Comment by wholesomedev** [comment]
👍

**Comment by forabi** [comment]
Closing
