### ISSUE TITLE
Use Flexbox for layout

### ISSUE THREAD

**Issue by msafih** [hollowverse/design#3]
We think using flexbox will make the layout CSS more maintainable. And it will help us avoid issues like a long name wrapping like this (See @forabi's comment [here](https://github.com/hollowverse/design/pull/2#issuecomment-321867022)):

![localhost-8080- iphone 6](https://user-images.githubusercontent.com/1012761/29223748-56dff9ec-7ed0-11e7-9486-ade7c13b1991.png)

That's why we think we should use flexbox instead of floating.

**Comment by Maxgrb** [comment]
@msafih according to #5, there isn't float positions there now. And I agree to using flexbox for further positioning.
