### ISSUE TITLE
Not enough space for long names in current layout on mobile

### ISSUE THREAD

**Issue by msafih** [hollowverse/design#5]
As @forabi [pointed out](https://github.com/hollowverse/design/pull/2#issuecomment-321867022), there isn't enough space for a long NP name like Arnold Schwarzenegger in the current mobile layout:

![](https://user-images.githubusercontent.com/1012761/29223748-56dff9ec-7ed0-11e7-9486-ade7c13b1991.png)

This screenshot is taken with iPhone 6. The same issue occurs on iPhone 6 Plus.

I'm not sure what the optimal solution for this is. One obvious solution is to put things in a centered column. 

<div align="center">
<p>The religion, politics and ideas of...</p>

<p>IMAGE OF ARNOLD SCHWARZENEGGER</p>

<p>Arnold Schwarznegger</p>
</div>

...but the issue with this layout is that the user has to scroll to get to the content they care about. But if you guys think that's okay, I'm fine with it.

**Comment by Maxgrb** [comment]
@msafih updated. Just one thing is propose to put "The religion, politics and ideas of..." right after image, because it makes composition stronger.
